/**
 * Vote for Farris API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagingArgs } from './pagingArgs';
import { SortDirection } from './sortDirection';


export interface BaseSearchModel { 
    OrderBy: string;
    SortDirection: SortDirection;
    Ordering: string;
    PagingArgs?: PagingArgs;
}
export namespace BaseSearchModel {
}


