/**
 * Vote for Farris API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagingArgs } from './pagingArgs';
import { SortDirection } from './sortDirection';


export interface GetAllVotesQuery { 
    OrderBy: string;
    SortDirection: SortDirection;
    Ordering: string;
    PagingArgs?: PagingArgs;
    VoterName?: string;
    VoteFor?: string;
    DateCreated?: string;
}
export namespace GetAllVotesQuery {
}


